apiVersion: v2
name: ecommerce-microservices
description: Helm Chart para E-Commerce Microservices en Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservices
  - ecommerce
  - spring-boot
  - kubernetes
maintainers:
  - name: E-Commerce Team
    email: team@ecommerce.local
sources:
  - https://github.com/SelimHorri/ecommerce-microservice-backend-app

